/*
  # Update founder types

  1. Changes
    - Update the valid_founder_types constraint with new categories
    - Safely migrate existing data to new categories
    - Add new constraint after data is updated

  2. Security
    - Maintains existing RLS policies
*/

-- First, temporarily disable the constraint
ALTER TABLE brands DROP CONSTRAINT IF EXISTS valid_founder_types;

-- Update existing records to match new types
DO $$ 
BEGIN
  -- Update records with exact matches first
  UPDATE brands SET type_of_influencer = 'Actor/Film Producer' WHERE type_of_influencer = 'Actor';
  UPDATE brands SET type_of_influencer = 'Beauty YouTuber' WHERE type_of_influencer = 'Beauty Creator';
  UPDATE brands SET type_of_influencer = 'Chef/TV Personality' WHERE type_of_influencer = 'Chef';
  UPDATE brands SET type_of_influencer = 'Content Creator' WHERE type_of_influencer = 'Creator';
  UPDATE brands SET type_of_influencer = 'Fashion Influencer' WHERE type_of_influencer = 'Fashion';
  UPDATE brands SET type_of_influencer = 'Gaming YouTuber' WHERE type_of_influencer = 'Gamer';
  UPDATE brands SET type_of_influencer = 'Lifestyle Influencer' WHERE type_of_influencer = 'Lifestyle';
  UPDATE brands SET type_of_influencer = 'Model/Influencer' WHERE type_of_influencer = 'Model';
  UPDATE brands SET type_of_influencer = 'Singer/Artist' WHERE type_of_influencer = 'Singer';
  UPDATE brands SET type_of_influencer = 'YouTuber/Influencer' WHERE type_of_influencer = 'YouTuber';
  
  -- Set any remaining unmatched records to a default
  UPDATE brands 
  SET type_of_influencer = 'Content Creator'
  WHERE type_of_influencer NOT IN (
    'Actor/Celebrity Influencer',
    'Actor/Film Producer',
    'Actor/Writer',
    'Actress/Entrepreneur',
    'Actress/Influencer',
    'Actress/Producer',
    'Actress/TV Personality',
    'Adventure/YouTube Influencer',
    'Animal/YouTuber',
    'Beauty Influencer',
    'Beauty YouTuber',
    'Beauty/LGBTQ+ Influencer',
    'Beauty/Lifestyle YouTuber',
    'Beauty/Nail YouTuber',
    'Beauty/YouTube Influencer',
    'Blogger-Turned-Entrepreneur',
    'Celebrity Hairstylist/Influencer',
    'Chef/TV Personality',
    'Chef/TV Personality/Influencer',
    'Comedy YouTubers',
    'Comedy/YouTube Influencer',
    'Content Creator',
    'DIY YouTubers',
    'DIY/YouTube Influencer',
    'Dancer/YouTube Influencer',
    'Esports/YouTuber',
    'Family/Gaming YouTubers',
    'Family/Hair Tutorial YouTuber',
    'Fashion Blogger/Influencer',
    'Fashion Influencer',
    'Fashion/Beauty YouTuber',
    'Fashion/Parenting Influencer',
    'Fashion/YouTube Influencer',
    'Fitness Athlete/Influencer',
    'Fitness Influencer',
    'Food Blogger/Influencer',
    'Food Blogger/YouTuber',
    'Food Influencer',
    'Food/Instagram Influencer',
    'Food/Nutrition YouTuber',
    'Former Pro Player/Streamer',
    'Former YouTuber',
    'Gaming Content Creator',
    'Gaming YouTuber',
    'Gaming YouTubers',
    'Gaming/Esports Influencers',
    'Gaming/YouTube Influencer',
    'Health/Food YouTuber',
    'Instagram Influencer/Photographer',
    'Instagram Meme Influencer',
    'Interior Designer/TV Personality',
    'Kids/YouTube Influencer',
    'Kids/YouTube Influencers',
    'Lifestyle Influencer',
    'Lifestyle YouTuber',
    'Lifestyle/Beauty Influencer',
    'Lifestyle/Beauty Influencers',
    'Lifestyle/Beauty YouTuber',
    'Lifestyle/YouTube Influencer',
    'Makeup Artist/Influencer',
    'Men''s Lifestyle YouTuber',
    'Model/Beauty Influencer',
    'Model/Influencer',
    'Musicians/Influencers',
    'Musicians/K-Pop Influencers',
    'News/YouTuber',
    'Pet/Instagram Influencer',
    'Podcast Host',
    'Rapper/Entertainer',
    'Rapper/Entrepreneur',
    'Rapper/Entrepreneur Influencer',
    'Rapper/Influencer',
    'Reality TV Star/Influencer',
    'Reality TV/Entrepreneur',
    'Reality TV/Influencer',
    'Reality/Model Influencer',
    'Science YouTuber',
    'Singer/Artist',
    'Singer/Artist Influencer',
    'Singer/Dancer',
    'Singer/Entertainer',
    'Singer/Entertainer Influencer',
    'Singer/Global Influencer',
    'Singer/Influencer',
    'Singer/Pop Culture Influencer',
    'Singer/Pop Influencer',
    'Singer/Reality Star',
    'Singer/Songwriter',
    'Singer/TV Personality',
    'Skincare YouTuber',
    'Spanish Gaming Influencer',
    'Sports/YouTube Influencer',
    'Stylist/Fashion Influencer',
    'Tech YouTuber',
    'TikToker',
    'TikToker/Influencer',
    'TikTokers',
    'Travel/Lifestyle YouTuber',
    'Travel/Minimalism YouTuber',
    'TV Host/Comedian',
    'TV Host/Comedian Influencer',
    'TV Host/Culinary Influencer',
    'TV Host/Influencer',
    'TV Personality/Author',
    'TV Personality/Influencer',
    'Twitch Streamers/Influencers',
    'Vegan/YouTube Influencer',
    'Wellness Influencer',
    'YouTuber',
    'YouTuber/Baker',
    'YouTuber/Comedian',
    'YouTuber/Designer',
    'YouTuber/Filmmaker',
    'YouTuber/Gaming',
    'YouTuber/Influencer',
    'YouTuber/Musician',
    'YouTuber/Philanthropist',
    'YouTuber/Podcaster',
    'YouTubers/Adventurers',
    'YouTubers/Boxers',
    'YouTubers/Comedians',
    'YouTubers/Gaming Influencers',
    'YouTubers/Pranksters'
  );
END $$;

-- Now add the constraint after the data has been updated
ALTER TABLE brands ADD CONSTRAINT valid_founder_types CHECK (
  type_of_influencer = ANY (ARRAY[
    'Actor/Celebrity Influencer',
    'Actor/Film Producer',
    'Actor/Writer',
    'Actress/Entrepreneur',
    'Actress/Influencer',
    'Actress/Producer',
    'Actress/TV Personality',
    'Adventure/YouTube Influencer',
    'Animal/YouTuber',
    'Beauty Influencer',
    'Beauty YouTuber',
    'Beauty/LGBTQ+ Influencer',
    'Beauty/Lifestyle YouTuber',
    'Beauty/Nail YouTuber',
    'Beauty/YouTube Influencer',
    'Blogger-Turned-Entrepreneur',
    'Celebrity Hairstylist/Influencer',
    'Chef/TV Personality',
    'Chef/TV Personality/Influencer',
    'Comedy YouTubers',
    'Comedy/YouTube Influencer',
    'Content Creator',
    'DIY YouTubers',
    'DIY/YouTube Influencer',
    'Dancer/YouTube Influencer',
    'Esports/YouTuber',
    'Family/Gaming YouTubers',
    'Family/Hair Tutorial YouTuber',
    'Fashion Blogger/Influencer',
    'Fashion Influencer',
    'Fashion/Beauty YouTuber',
    'Fashion/Parenting Influencer',
    'Fashion/YouTube Influencer',
    'Fitness Athlete/Influencer',
    'Fitness Influencer',
    'Food Blogger/Influencer',
    'Food Blogger/YouTuber',
    'Food Influencer',
    'Food/Instagram Influencer',
    'Food/Nutrition YouTuber',
    'Former Pro Player/Streamer',
    'Former YouTuber',
    'Gaming Content Creator',
    'Gaming YouTuber',
    'Gaming YouTubers',
    'Gaming/Esports Influencers',
    'Gaming/YouTube Influencer',
    'Health/Food YouTuber',
    'Instagram Influencer/Photographer',
    'Instagram Meme Influencer',
    'Interior Designer/TV Personality',
    'Kids/YouTube Influencer',
    'Kids/YouTube Influencers',
    'Lifestyle Influencer',
    'Lifestyle YouTuber',
    'Lifestyle/Beauty Influencer',
    'Lifestyle/Beauty Influencers',
    'Lifestyle/Beauty YouTuber',
    'Lifestyle/YouTube Influencer',
    'Makeup Artist/Influencer',
    'Men''s Lifestyle YouTuber',
    'Model/Beauty Influencer',
    'Model/Influencer',
    'Musicians/Influencers',
    'Musicians/K-Pop Influencers',
    'News/YouTuber',
    'Pet/Instagram Influencer',
    'Podcast Host',
    'Rapper/Entertainer',
    'Rapper/Entrepreneur',
    'Rapper/Entrepreneur Influencer',
    'Rapper/Influencer',
    'Reality TV Star/Influencer',
    'Reality TV/Entrepreneur',
    'Reality TV/Influencer',
    'Reality/Model Influencer',
    'Science YouTuber',
    'Singer/Artist',
    'Singer/Artist Influencer',
    'Singer/Dancer',
    'Singer/Entertainer',
    'Singer/Entertainer Influencer',
    'Singer/Global Influencer',
    'Singer/Influencer',
    'Singer/Pop Culture Influencer',
    'Singer/Pop Influencer',
    'Singer/Reality Star',
    'Singer/Songwriter',
    'Singer/TV Personality',
    'Skincare YouTuber',
    'Spanish Gaming Influencer',
    'Sports/YouTube Influencer',
    'Stylist/Fashion Influencer',
    'Tech YouTuber',
    'TikToker',
    'TikToker/Influencer',
    'TikTokers',
    'Travel/Lifestyle YouTuber',
    'Travel/Minimalism YouTuber',
    'TV Host/Comedian',
    'TV Host/Comedian Influencer',
    'TV Host/Culinary Influencer',
    'TV Host/Influencer',
    'TV Personality/Author',
    'TV Personality/Influencer',
    'Twitch Streamers/Influencers',
    'Vegan/YouTube Influencer',
    'Wellness Influencer',
    'YouTuber',
    'YouTuber/Baker',
    'YouTuber/Comedian',
    'YouTuber/Designer',
    'YouTuber/Filmmaker',
    'YouTuber/Gaming',
    'YouTuber/Influencer',
    'YouTuber/Musician',
    'YouTuber/Philanthropist',
    'YouTuber/Podcaster',
    'YouTubers/Adventurers',
    'YouTubers/Boxers',
    'YouTubers/Comedians',
    'YouTubers/Gaming Influencers',
    'YouTubers/Pranksters'
  ])
);