/*
  # Add Athlete/Influencer to valid founder types

  1. Changes
    - Add 'Athlete/Influencer' to the valid_founder_types constraint
    - Preserve all existing valid types
    - Ensure alphabetical ordering of types

  2. Impact
    - Allows brands with 'Athlete/Influencer' type to be processed
    - No data loss or modification of existing records
*/

ALTER TABLE brands DROP CONSTRAINT IF EXISTS valid_founder_types;

ALTER TABLE brands ADD CONSTRAINT valid_founder_types
  CHECK (
    type_of_influencer = ANY (ARRAY[
      'Actor/Celebrity Influencer',
      'Actor/Film Producer',
      'Actor/Writer',
      'Actress/Entrepreneur',
      'Actress/Influencer',
      'Actress/Producer',
      'Actress/TV Personality',
      'Adventure/YouTube Influencer',
      'Animal/YouTuber',
      'Athlete/Influencer',
      'Beauty Influencer',
      'Beauty YouTuber',
      'Beauty/LGBTQ+ Influencer',
      'Beauty/Lifestyle YouTuber',
      'Beauty/Nail YouTuber',
      'Beauty/YouTube Influencer',
      'Blogger-Turned-Entrepreneur',
      'Celebrity Hairstylist/Influencer',
      'Chef/TV Personality',
      'Chef/TV Personality/Influencer',
      'Comedy YouTubers',
      'Comedy/YouTube Influencer',
      'Content Creator',
      'DIY YouTubers',
      'DIY/YouTube Influencer',
      'Dancer/YouTube Influencer',
      'Esports/YouTuber',
      'Family/Gaming YouTubers',
      'Family/Hair Tutorial YouTuber',
      'Fashion Blogger/Influencer',
      'Fashion Influencer',
      'Fashion/Beauty YouTuber',
      'Fashion/Parenting Influencer',
      'Fashion/YouTube Influencer',
      'Fitness Athlete/Influencer',
      'Fitness Influencer',
      'Food Blogger/Influencer',
      'Food Blogger/YouTuber',
      'Food Influencer',
      'Food/Instagram Influencer',
      'Food/Nutrition YouTuber',
      'Former Pro Player/Streamer',
      'Former YouTuber',
      'Gaming Content Creator',
      'Gaming YouTuber',
      'Gaming YouTubers',
      'Gaming/Esports Influencers',
      'Gaming/YouTube Influencer',
      'Health/Food YouTuber',
      'Instagram Influencer/Photographer',
      'Instagram Meme Influencer',
      'Interior Designer/TV Personality',
      'Kids/YouTube Influencer',
      'Kids/YouTube Influencers',
      'Lifestyle Influencer',
      'Lifestyle YouTuber',
      'Lifestyle/Beauty Influencer',
      'Lifestyle/Beauty Influencers',
      'Lifestyle/Beauty YouTuber',
      'Lifestyle/YouTube Influencer',
      'Makeup Artist/Influencer',
      'Men''s Lifestyle YouTuber',
      'Model/Beauty Influencer',
      'Model/Influencer',
      'Musicians/Influencers',
      'Musicians/K-Pop Influencers',
      'News/YouTuber',
      'Pet/Instagram Influencer',
      'Podcast Host',
      'Rapper/Entertainer',
      'Rapper/Entrepreneur',
      'Rapper/Entrepreneur Influencer',
      'Rapper/Influencer',
      'Reality TV Star/Influencer',
      'Reality TV/Entrepreneur',
      'Reality TV/Influencer',
      'Reality/Model Influencer',
      'Science YouTuber',
      'Singer/Artist',
      'Singer/Artist Influencer',
      'Singer/Dancer',
      'Singer/Entertainer',
      'Singer/Entertainer Influencer',
      'Singer/Global Influencer',
      'Singer/Influencer',
      'Singer/Pop Culture Influencer',
      'Singer/Pop Influencer',
      'Singer/Reality Star',
      'Singer/Songwriter',
      'Singer/TV Personality',
      'Skincare YouTuber',
      'Spanish Gaming Influencer',
      'Sports/YouTube Influencer',
      'Stylist/Fashion Influencer',
      'Tech YouTuber',
      'TikToker',
      'TikToker/Influencer',
      'TikTokers',
      'Travel/Lifestyle YouTuber',
      'Travel/Minimalism YouTuber',
      'TV Host/Comedian',
      'TV Host/Comedian Influencer',
      'TV Host/Culinary Influencer',
      'TV Host/Influencer',
      'TV Personality/Author',
      'TV Personality/Influencer',
      'Twitch Streamers/Influencers',
      'Vegan/YouTube Influencer',
      'Wellness Influencer',
      'YouTuber',
      'YouTuber/Baker',
      'YouTuber/Comedian',
      'YouTuber/Designer',
      'YouTuber/Filmmaker',
      'YouTuber/Gaming',
      'YouTuber/Influencer',
      'YouTuber/Musician',
      'YouTuber/Philanthropist',
      'YouTuber/Podcaster',
      'YouTubers/Adventurers',
      'YouTubers/Boxers',
      'YouTubers/Comedians',
      'YouTubers/Gaming Influencers',
      'YouTubers/Pranksters'
    ])
  );